issuesOpened: >
  Thank you for raising this issue! We will try and get back to you as soon as possible.

  Please make sure you format it properly and have given us as much context as possible.
  
  Hey @tunnckoCore, check out this one too! ;)

pullRequestOpened: >
  Thank you for raising your pull request.

  Please make sure again that you have followed our [contributing guidelines]() and the [code of conduct]().
  We will review it as soon as possible.
  
  Hey @tunnckoCore, check out this one too! ;)
