version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

restore_modules_cache: &restore_modules_cache
  restore_cache:
    keys:
      - repo-v1-{{ checksum "yarn.lock" }}
      - repo-v1-
      # fallback to using the latest cache if no exact match is found
      - repo-

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Installing dependencies
          command: yarn setup:ci
      - save_cache:
          key: repo-v1--{{ checksum "yarn.lock" }}
          paths: node_modules
      - run:
          name: Remove node_modules to cleanup workspace
          command: rm -rf node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Running tests
          command: yarn start test
      - run:
          name: Sending test coverage to CodeCov
          command: bash <(curl -s https://codecov.io/bash)

  lint:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Linting with ESLint and Prettier
          command: yarn start lint

  docs:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Documentation
          command: yarn start docs

  format:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Formatting with Prettier
          command: yarn start format

  # release:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - *restore_modules_cache
  #     - run:
  #         name: Releasing and publishing
  #         command: yarn run release

workflows:
  version: 2
  automated:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - lint
      - format:
          requires:
            - lint
      - docs:
          requires:
            - format
      # - release:
      #     requires:
      #       - docs
      #       - test
      #     filters:
      #       branches:
      #         only: master
      #     context: org-global
